name: pushswap
run-name: Running on ${{ github.repository }} by @${{ github.actor }}

env:
  MIRROR_URL: git@github.com:Jabolol/pushswap.git

on: [push, pull_request]

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'Jabolol/pushswap-aux'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0x7fffffff
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:Jabolol/pushswap.git
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
